### ISSUE TITLE
[Falha] - UI - Alerta de erro preenchimento de campo

### ISSUE THREAD

**Issue by lcarneirofb** [fabioafreitas/Projeto_Desenvolvimento_Web#50]
Data: 07/06/2019
Hora: 23:38 PM
-------------------------------------------
Passos para reprodução
-------------------------------------------
Pré-Condições:
1- Estar na página de registro de ocorrência
-------------------------------------------
Passos:
1- Aperte no botão <Registrar Ocorrencia>
-------------------------------------------
Resultado Esperado:
- O sistema retorna uma mensagem de erro solicitando que o usuário preencha o campo, como visto em: ![Error_message_MYALERT](https://user-images.githubusercontent.com/33436382/59141111-c923e180-897d-11e9-98c3-72f27848dd2f.png)
-------------------------------------------
Resultado Atual:
- O sistema não mostra nenhuma mensagem de erro

**Comment by GabrielAlbq** [comment]
Vê se essa nova versão desse último commit resolve teu problema: https://github.com/fabioafreitas/Projeto_Desenvolvimento_Web/commit/51850a900af7adac90d7cce987d27b624a63eb80

**Comment by lcarneirofb** [comment]
Resolveu! 
Obrigado, o Caso de Teste será colocado para Reteste.

Atenciosamente, 
Lucas Carneiro
