### ISSUE TITLE
[Falha] - UI - Botão com Texto errado

### ISSUE THREAD

**Issue by lcarneirofb** [fabioafreitas/Projeto_Desenvolvimento_Web#51]
Data: 08/06/2019
Hora: 00:01 AM
-------------------------------------------
Passos para reprodução
-------------------------------------------
Pré-Condições:
1- Estar na página de Registro de Ocorrência
-------------------------------------------
Passos:
1- Observe o botão azul na parte inferior da tela
-------------------------------------------
Resultado Esperado:
- O botão diz <Registrar Ocorrência>
-------------------------------------------
Resultado Atual:
- O botão diz < Registrar Ocorrencai > como visto em
![Screenshot_16](https://user-images.githubusercontent.com/33436382/59141306-c8407f00-8980-11e9-8f13-c18449d43ef8.png)

**Comment by GabrielAlbq** [comment]
Corrigido no commit: https://github.com/fabioafreitas/Projeto_Desenvolvimento_Web/commit/b08dc84aedace39457c86a4a02e06073673d266c
