### ISSUE TITLE
[BUG] - [Restrições] - Uma ocorrência pode ser criada numa data posterior

### ISSUE THREAD

**Issue by lcarneirofb** [fabioafreitas/Projeto_Desenvolvimento_Web#57]
Data:09/06/2019
Hora: 22:17 PM
-------------------------------------------
Passos para reprodução
-------------------------------------------
Pré-Condições:
1- Estar logado como usuário
2- Estar na página de Registro de Ocorrência
-------------------------------------------
Passos:
1- Preencha o Título da Ocorrência
2- Selecione uma data posterior à data atual
3- Preencha o campo Comentário da Ocorrência
4- Clique em < Registrar Ocorrencia>
-------------------------------------------
Resultado Esperado:
- O sistema mostra uma mensagem dizendo que não é possível criar uma ocorrência para datas posteriores
-------------------------------------------
Resultado Atual:
- O sistema não exibe nenhuma mensagem, e manda uma solicitação de criação para o Banco de Dados

**Comment by GabrielAlbq** [comment]
Fixed https://github.com/fabioafreitas/Projeto_Desenvolvimento_Web/commit/9f8c9fb0082954262c295669e1c56e2616d86c1e, não coloquei para mostrar uma mensagem porque já bloqueia antes da pessoa selecionar.
