### ISSUE TITLE
Cadastrar ocorrência

### ISSUE THREAD

**Issue by AmauryTavares** [fabioafreitas/Projeto_Desenvolvimento_Web#63]
A opção de cadastrar ocorrência não mostra nenhum mensagem/ação sobre o resultado da operação.

**Comment by GabrielAlbq** [comment]
Fixed: https://github.com/fabioafreitas/Projeto_Desenvolvimento_Web/commit/9f8c9fb0082954262c295669e1c56e2616d86c1e
