### ISSUE TITLE
[Bug] - UI - Botão cadastre-se não funciona

### ISSUE THREAD

**Issue by cham1236** [fabioafreitas/Projeto_Desenvolvimento_Web#66]
Data: 10 - junho - 2019
Hora: 16:43

Pré-condição 

1 - Ter o projeto rodando

Passos:

1 - Na pagina inicial role ate o fim da página
2 - Clique no botão Cadastre-se

Resultado esperado

- O usuário é levado para a página de cadastro

Resultado Atual

- O botão não funciona

**Comment by GabrielAlbq** [comment]
Fixed https://github.com/fabioafreitas/Projeto_Desenvolvimento_Web/commit/9f8c9fb0082954262c295669e1c56e2616d86c1e
