### ISSUE TITLE
[Bug] - UI - Cards de dúvida não respondem corretamente

### ISSUE THREAD

**Issue by cham1236** [fabioafreitas/Projeto_Desenvolvimento_Web#67]
Data: 10 - junho - 2019
Hora: 16:49

Pré-condição

1 - Ter o projeto rodando

Passos:

1 - Na pagina inicial clique em dúvidas frequentes
2 - Clique no card 5

Resultado esperado

Apenas o card 5 deve ser aberto e qualquer outro card é fechado

Resultado Atual

Varios cards são abertos aleatoriamente

**Comment by GabrielAlbq** [comment]
Fixed https://github.com/fabioafreitas/Projeto_Desenvolvimento_Web/commit/9f8c9fb0082954262c295669e1c56e2616d86c1e
